#!/usr/bin/env bash

count=0

ID="$(ip -o link | awk -F': ' '/state UP/ {print $2; exit}')"
WIFI_IFACE="$(iw dev | awk '$1 == "Interface" {print $2; exit}')"
SSID="$(iw dev "$WIFI_IFACE" link 2>/dev/null | awk -F': ' '/SSID/ {print $2; exit}')"

truncate_ssid() {
    local ssid="$1"
    if [[ ${#ssid} -gt 8 ]]; then
        echo "${ssid:0:7}.."
    else
        echo "$ssid"
    fi
}

net_stat () {
    if ip route show default | grep -q .; then
        if [[ $ID == e* ]]; then
            echo "Online"
            echo "images/icons/system/wifi.png"
        else
            truncated_ssid=$(truncate_ssid "$SSID")
            echo "${truncated_ssid:-Wi-Fi}"
            echo "images/icons/system/wifi.png"
        fi
    else
        echo "Offline"
        echo "images/icons/system/no-wifi.png"
    fi
}

if [[ $1 == '--stat' ]]; then
    net_stat | head -n1
elif [[ $1 == '--icon' ]]; then
    net_stat | tail -n1
fi
