import assert from 'node:assert/strict';
import path from 'node:path';
import { pathToFileURL, fileURLToPath } from 'node:url';
const root = process.env.PI_PACKAGE_DIR || '/opt/homebrew/Cellar/pi-coding-agent/0.85.1/libexec/lib/node_modules/@earendil-works/pi-coding-agent';
const mod = rel => import(pathToFileURL(path.join(root, rel)));
const { discoverAndLoadExtensions } = await mod('dist/core/extensions/loader.js');
const { ToolExecutionComponent, createBashToolDefinition } = await mod('dist/index.js');
const { loadThemeFromPath, setThemeInstance } = await mod('dist/modes/interactive/theme/theme.js');
const { visibleWidth, stripTerminalSequences } = await mod('node_modules/@earendil-works/pi-tui/dist/index.js');
const agent = fileURLToPath(new URL('../../', import.meta.url));
const theme = loadThemeFromPath(path.join(agent, 'themes/tokyonight-muted.json'), 'truecolor');
setThemeInstance(theme);
const result = await discoverAndLoadExtensions([], process.cwd(), agent);
assert.deepEqual(result.errors, []);
const ext = result.extensions.find(e => e.path.includes('/compact-shell/'));
assert(ext);
const original = ToolExecutionComponent.prototype.render;
const ctx = { hasUI: true, mode: 'tui', ui: { theme } };
for (const fn of ext.handlers.get('session_start')) await fn({reason:'startup'},ctx);
const tool = new ToolExecutionComponent('bash','test',{command:'echo 日本語\n'.repeat(30)}, {},createBashToolDefinition(process.cwd()),{requestRender(){}},process.cwd());
tool.updateResult({content:[{type:'text',text:Array.from({length:40},(_,i)=>`line ${i} 日本語`).join('\n')}],isError:false});
for (const width of [12,40,79,80,120,200]) {
  const rows = tool.render(width);
  assert(rows.length <= 7);
  assert(rows.every(row => visibleWidth(row) <= width));
  const indent = width >= 80 ? width - Math.min(88, Math.floor(width * 0.7)) : 0;
  assert(stripTerminalSequences(rows[1]).startsWith(' '.repeat(indent) + '│ '));
}
const collapsed = tool.render(120);
assert.equal(tool.handleMouse({type:'click',button:'left',x:100,y:2,width:120,height:7}).handled,true);
assert(tool.render(120).length > collapsed.length);
tool.setExpanded(false);
tool.updateResult({content:[{type:'text',text:'failure details\n'.repeat(40)}],isError:true});
assert(tool.render(120).length > 7);
const read = new ToolExecutionComponent('read','read',{path:'example'}, {},undefined,{requestRender(){}},process.cwd());
assert.deepEqual(read.render(120),original.call(read,120));
for (const fn of ext.handlers.get('session_shutdown')) await fn({reason:'reload'},ctx);
assert.equal(ToolExecutionComponent.prototype.render,original);
console.log('PASS: theme loads; compact shell, CJK widths, right alignment, click expansion, full errors, other tools unchanged, reload cleanup');
console.log(collapsed.map(stripTerminalSequences).join('\n'));
process.exit(0);
