monitor = DP-3,3840x2160@75,0x0,1.5
monitor = HDMI-A-1,1920x1080@164.995,2560x540,1
monitor = ,preferred,auto,1

workspace = 1, monitor:DP-3, default:true, persistent:true
workspace = 2, monitor:DP-3, persistent:true
workspace = 3, monitor:DP-3, persistent:true
workspace = 4, monitor:DP-3, persistent:true
workspace = 5, monitor:DP-3, persistent:true
workspace = 6, monitor:HDMI-A-1, default:true, persistent:true
workspace = 7, monitor:HDMI-A-1, persistent:true
workspace = 8, monitor:HDMI-A-1, persistent:true
workspace = 9, monitor:HDMI-A-1, persistent:true
workspace = special:main, monitor:DP-3
workspace = special:side, monitor:HDMI-A-1
