#!/bin/bash

SKETCHYBAR_BIN="/opt/homebrew/bin/sketchybar"
AEROSPACE_BIN="/opt/homebrew/bin/aerospace"
PLUGIN_DIR="$CONFIG_DIR/plugins"

bar=(
  position=top
  display=all
  height=36
  margin=10
  y_offset=6
  corner_radius=8
  blur_radius=36
  color=0xd8181a20
  border_width=1
  border_color=0x30d7f7ff
  padding_left=12
  padding_right=12
  sticky=on
  topmost=window
  shadow=on
  font_smoothing=on
)
"$SKETCHYBAR_BIN" --bar "${bar[@]}"

default=(
  updates=when_shown
  drawing=on
  icon.drawing=off
  label.color=0xfff5f7fa
  label.highlight_color=0xffffffff
  label.font="CaskaydiaCove Nerd Font:SemiBold:12.0"
  label.padding_left=10
  label.padding_right=10
  background.drawing=on
  background.height=26
  background.corner_radius=6
  background.color=0x1affffff
  background.border_width=1
  background.border_color=0x14ffffff
  blur_radius=0
  padding_left=3
  padding_right=3
)
"$SKETCHYBAR_BIN" --default "${default[@]}"

"$SKETCHYBAR_BIN" --add event aerospace_workspace_change

for sid in $("$AEROSPACE_BIN" list-workspaces --all --format '%{workspace}'); do
  item=(
    label="$sid"
    script="$PLUGIN_DIR/workspace.sh"
    click_script="$AEROSPACE_BIN workspace $sid"
  )

  "$SKETCHYBAR_BIN" --add item "space.$sid" left \
                    --set "space.$sid" "${item[@]}" \
                    --subscribe "space.$sid" aerospace_workspace_change mouse.entered mouse.exited
done

front_app=(
  width=220
  label.max_chars=24
  label.align=left
  label.color=0xfff5f7fa
  background.color=0x14121418
  background.border_color=0x20ffffff
  script="$PLUGIN_DIR/front_app.sh"
)
"$SKETCHYBAR_BIN" --add item front_app left \
                  --set front_app "${front_app[@]}" \
                  --subscribe front_app front_app_switched

battery=(
  update_freq=60
  background.color=0x15121418
  background.border_color=0x18ffffff
  label.padding_left=0
  script="$PLUGIN_DIR/battery.sh"
)
"$SKETCHYBAR_BIN" --add item battery right \
                  --set battery "${battery[@]}" \
                  --subscribe battery power_source_change system_woke

clock=(
  update_freq=30
  background.color=0x15121418
  background.border_color=0x18ffffff
  label.color=0xfff5f7fa
  label.padding_left=0
  script="$PLUGIN_DIR/clock.sh"
)
"$SKETCHYBAR_BIN" --add item clock right \
                  --set clock "${clock[@]}"

"$SKETCHYBAR_BIN" --update
"$SKETCHYBAR_BIN" --trigger aerospace_workspace_change \
                  FOCUSED="$("$AEROSPACE_BIN" list-workspaces --focused --format '%{workspace}')"
