#!/bin/bash

SKETCHYBAR_BIN="/opt/homebrew/bin/sketchybar"
AEROSPACE_BIN="/opt/homebrew/bin/aerospace"
PLUGIN_DIR="$CONFIG_DIR/plugins"

bar=(
  position=top
  display=all
  height=34
  margin=8
  y_offset=4
  corner_radius=8
  blur_radius=28
  color=0x6bf8f7f2
  border_width=1
  border_color=0x42ffffff
  padding_left=10
  padding_right=10
  sticky=on
  topmost=window
  shadow=on
  font_smoothing=on
)
"$SKETCHYBAR_BIN" --bar "${bar[@]}"

default=(
  updates=when_shown
  drawing=on
  icon.drawing=off
  label.color=0xff1d1d1f
  label.highlight_color=0xff1d1d1f
  label.font="CaskaydiaCove Nerd Font:SemiBold:12.0"
  label.padding_left=10
  label.padding_right=10
  background.drawing=on
  background.height=24
  background.corner_radius=6
  background.color=0x24ffffff
  background.border_width=0
  blur_radius=0
  padding_left=3
  padding_right=3
)
"$SKETCHYBAR_BIN" --default "${default[@]}"

"$SKETCHYBAR_BIN" --add event aerospace_workspace_change

for sid in $("$AEROSPACE_BIN" list-workspaces --all --format '%{workspace}'); do
  item=(
    label="$sid"
    script="$PLUGIN_DIR/workspace.sh"
    click_script="$AEROSPACE_BIN workspace $sid"
  )

  "$SKETCHYBAR_BIN" --add item "space.$sid" left \
                    --set "space.$sid" "${item[@]}" \
                    --subscribe "space.$sid" aerospace_workspace_change mouse.entered mouse.exited
done

front_app=(
  width=260
  label.max_chars=28
  label.align=center
  background.color=0x18ffffff
  script="$PLUGIN_DIR/front_app.sh"
)
"$SKETCHYBAR_BIN" --add item front_app center \
                  --set front_app "${front_app[@]}" \
                  --subscribe front_app front_app_switched

battery=(
  update_freq=60
  label.padding_left=0
  script="$PLUGIN_DIR/battery.sh"
)
"$SKETCHYBAR_BIN" --add item battery right \
                  --set battery "${battery[@]}" \
                  --subscribe battery power_source_change system_woke

clock=(
  update_freq=30
  label.padding_left=0
  script="$PLUGIN_DIR/clock.sh"
)
"$SKETCHYBAR_BIN" --add item clock right \
                  --set clock "${clock[@]}"

"$SKETCHYBAR_BIN" --update
"$SKETCHYBAR_BIN" --trigger aerospace_workspace_change \
                  FOCUSED="$("$AEROSPACE_BIN" list-workspaces --focused --format '%{workspace}')"
